---
- name: Install EPEL repo for step 2
  yum:
    name: epel-release
    state: present
- name: Clean yum cache
  command: yum clean all
- name: Update metadata
  command: yum update -y
- name: Add the repo to yum install
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    disable_gpg_check: yes
    state: present
- name: Update all packages
  yum:
    name: "*"
    state: latest
- name: Download and install python
  yum:
    name:
      - python36u
      - python36u-libs
      - python36u-devel
      - python36u-pip
    state:
      present 

